export interface staffModal {
    staff_type: String,
    firstName: String,
    middleName: String,
    lastName: String,
    NickName: String,
    gender: String,
    doB: String,
    file_attach1: String,
    file_attach1_hidden:String
    phoneNumber: String,
    email: String,
    password: String,
    permaAdrr: String,
    permaCity: String,
    staffstateCurrent: String,
    permaPostalCode: String,
    attachFile: String,
    attachFile_hidden: String,
    language: String,
    english_level_type: String,
    english_level_date: String,
    stffSignature: String,
    terms: String,
    ticket_id: String,
    status: Number,
}