var mongoose = require('mongoose');
var NewInstructorSchema = new mongoose.Schema({
  role_id: Number,
  role_name: String,
  personal_details: {},
  address_details: {},
  license_frtol: {},
  license_coprtr: {},
  license_ppl: {},
  license_cpl: {},
  license_chpl: {},
  license_atpl: {},
  license_ir: {},
  rating_afi: {},
  rating_fir: {},
  rating_dcfi: {},
  rating_cfi: {},
  certificates_medical: {},
  certificates_refresher: {},
  certificates_avsec: {},
  exp_single_engine: {},
  exp_multi_engine: {},
  hours_flown_single: {},
  hours_flown_multi: {},
  instrument: {},
  language: String,
  english_level_type1: String,
  languageDate: String,
  InstSignature: String,
  ticket_id: String,
  status: Number,
  Created_date: { type: Date, default: Date.now },
  modify_date: { type: Date, default: Date.now }
});
mongoose.model('NewInstructor', NewInstructorSchema);