var mongoose = require("mongoose");
var studentSchema = new mongoose.Schema({
  role_id: Number,
  role_name: String,
  typeOfStudent: String,
  personal_details: {},
  address_details: {},
  parent_guardian_information:{},
  license_spl: {},
  license_frtol: {},
  license_frtol_r: {},
  license_ppl: {},
  license_cpl: {},
  license_chpl: {},
  license_atpl: {},
  license_ir: {},
  license_coprtr: {},
  certificates_medical: {},
  certificates_refresher: {},
  certificates_avsec: {},
  exp_single_engine: {},
  exp_multi_engine: {},
  hours_flown_single: {},
  hours_flown_multi: {},
  instrument: {},
  attachFile:String,
  language: String,
  english_level_type: String,
  english_level_date: String,
  terms: String,
  stdSignature: String,
  ticket_id: String,
  status: Number,
  Created_date: { type: Date, default: Date.now }
//   typeOfStudent: String,
//   firstName: String,
//   middleName: String,
//   lastName: String,
//   NickName: String,
//   stdSignature: String,
//   gender: String,
//   doB: String,
//   bloodgroup: String,
//   allergies: String,
//   healthInsurance: String,
//   phoneNumber: String,
//   email: String,
//   currAddr: String,
//   currCity: String,
//   currCountry: String,
//   currPostalCode: String,
//   permaAdrr: String,
//   permaCity: String,
//   permaCountry: String,
//   permaPostalCode: String,
//   guardianFName: String,
//   guardianMName: String,
//   guardianLName: String,
//   guardianPhone: String,
//   guardianEmail: String,
//   SPL_license: String,
//   lt_spl_type1: String,
//   lt_spl_file1: String,
//   lt_spl_date1: String,
//   FRTOL_license: String,
//   lt_FRTOL_type1: String,
//   lt_FRTOL_file1: String,
//   lt_FRTOL_date1: String,
//   FRTOLR_license: String,
//   lt_FRTOLR_type1: String,
//   lt_FRTOLR_file1: String,
//   lt_FRTOLR_date1: String,
//   PPL_license: String,
//   lt_ppl_type1: String,
//   lt_ppl_file1: String,
//   lt_ppl_date1: String,
//   CPL_license: String,
//   lt_INcpl_type1: String,
//   lt_INcpl_file1: String,
//   lt_INcpl_date1: String,
//   lt_FNcpl_type1: String,
//   lt_FNcpl_file1: String,
//   lt_FNcpl_date1: String,
//   CHPL_license: String,
//   lt_INCHPL_type1: String,
//   lt_INCHPL_file1: String,
//   lt_INCHPL_date1: String,
//   lt_FNCHPL_type1: String,
//   lt_FNCHPL_file1: String,
//   lt_FNCHPL_date1: String,
//   ATPL_license: String,
//   lt_INATPL_type1: String,
//   lt_INATPL_file1: String,
//   lt_INATPL_date1: String,
//   lt_FNATPL_type1: String,
//   lt_FNATPL_file1: String,
//   lt_FNATPL_date1: String,
//   IR_license: String,
//   lt_ir_type1: String,
//   lt_ir_file1: String,
//   lt_ir_date1: String,
//   Medical_license: String,
//   cert_med_type1: String,
//   cert_med_file1: String,
//   cert_med_date1: String,
//   Refresher_license: String,
//   cert_refresh_type1: String,
//   cert_refresh_file1: String,
//   cert_refresh_location: String,
//   AVSEC_license: String,
//   cert_avsec_date1: String,
//   cert_avsec_file1: String,
//   cert_avsec_type1: String,
//   single1: String,
//   single2: String,
//   single3: String,
//   single4: String,
//   single5: String,
//   single6: String,
//   multi1: String,
//   multi2: String,
//   multi3: String,
//   multi4: String,
//   multi5: String,
//   multi6: String,
//   singleDayHours: String,
//   singleDayMin: String,
//   singleDayPICHours: String,
//   singleDayPICMin: String,
//   singleNightHours: String,
//   singleNightMin: String,
//   singleNightPICHours: String,
//   singleNightPICMin: String,
//   multiDayHours: String,
//   multiDayMin: String,
//   multiDayPICHours: String,
//   multiDayPICMin: String,
//   multiNightHours: String,
//   multiNightMin: String,
//   multiNightPICHours: String,
//   multiNightPICMin: String,
//   instActualHours: String,
//   instAutualMin: String,
//   StimuAutualHours: String,
//   StimuAutualMin: String,
//   attachFile: String,
//   lt_coprtr_file: String,
//   lt_ppl_Expiry_date: String,
//   lt_INcpl_Expiry_date: String,
//   lt_FNcpl_Expiry_date: String,
//   lt_INCHPL_Expiry_date: String,
//   lt_FNCHPL_Expiry_date: String,
//   lt_INATPL_Expiry_date: String,
//   lt_FNATPL_Expiry_date: String,
//   lt_coprtr_Expiry_date: String,
//   lt_ir_Expiry_date: String,
//   lt_coprtr_type1: String,
//   lt_coprtr_date1: String,
//   COPRTR_license: String,
//   language: String,
//   english_level_type: String,
//   english_level_date: String,
//   terms: String,
//   file_attach1:String,
//   password:String,
//   stateCurrent:String,
//   statepermanent:String,
//   lt_spl_Expiry_date:String,
//   lt_FRTOL_Expiry_date1:String,
//   lt_FRTOLR_Expiry_date1:String,
//   lt_coprtr_file1:String,
//   cert_med_date2:String,
//   created: {
//     type: Date,
//     default: Date.now
//   }
// });
});
mongoose.model("NewStudent", studentSchema);
