var mongoose = require("mongoose");
//-var crypto = require("crypto");

var NewUsersModelSchema = new mongoose.Schema({
    role_id: Number,
    role_name: String,
    email: String,
    password: String,
    student_type: String,
    personal_details: {},
    parent_guardian_information: {},
    address_details: {},
    license_spl: {},
    license_frtol_r: {},
    license_frtol: {},
    license_coprtr: {},
    license_ppl: {},
    license_cpl: {},
    license_chpl: {},
    license_atpl: {},
    license_ir: {},
    rating_afi: {},
    rating_fir: {},
    rating_dcfi: {},
    rating_cfi: {},
    certificates_medical: {},
    certificates_refresher: {},
    certificates_avsec: {},
    exp_single_engine: {},
    exp_multi_engine: {},
    hours_flown_single: {},
    hours_flown_multi: {},
    instrument: {},
    attach_log_book: String,
    language: String,
    english_level_type1: String,
    languageDate: String,
    user_signature: String,
    ticket_id: String,
    status: Number,
    terms: String,
    created_date: { type: Date, default: Date.now },
    modify_date: { type: Date, default: Date.now }
});
mongoose.model("user_model", NewUsersModelSchema);
